### ISSUE TITLE
Better adhere to BUILD_SHARED_LIBS instead of enforcing shared build?

### ISSUE THREAD

**Issue by swillner** [ecmwf/eckit#41]
I am trying to statically link against libeckit, but, unfortunately, it is hard-coded to be built shared-only:
https://github.com/ecmwf/eckit/blob/20c6b9ca04a058f68f6521f81b332764dfb06486/src/eckit/CMakeLists.txt#L909
Is it possible to lift this to follow the `BUILD_SHARED_LIBS` option (as in https://github.com/ecmwf/ecbuild/blob/77ad783236c72e66c449a8b58000b751807c80f3/cmake/ecbuild_add_library.cmake#L645 when the build `TYPE` is not explicitely given)? When removing the enforcing line, eckit (and my executable) build fine... Thank you!

**Comment by tlmquintino** [comment]
The reason for eckit to be forcefully build as a shared library is that it part of its functionality will be broken if built as a static library. We use the method in the class LibEckit::addr() to introspect the location of the library location.
If built statically, this will break as it will return the location of the executable.
Can I ask in return why are you trying to link statically?

**Comment by swillner** [comment]
Hmm, that is a pity. Do you do the `addr` in every case?
I want to link statically to ease with dependency management and bundle everything "code" (eckit, metkit, fdb) in the executable. Nothing super-urgent or important, though.
Btw, I am working at MPI-M in the ACROSS project and am already in contact with Emanuele ;)

**Comment by swillner** [comment]
As far as I can see `addr` is only used to find configuration files relative to the library, which I don't want to rely on anyway. Overall, the static build works fine. Unfortunately, the factories/registration of build object in the factories in eckit, metkit, and fdb rely on static initalization before the `main()` function. I am not sure if this guaranteed even in shared libraries (https://isocpp.org/wiki/faq/ctors#static-init-order), though it seems to work fine in that case. For static linking I have to use `-Wl,--whole-archive`. If you were to refactor to have a central registration of the builder objects, I would be happy to help out.

**Comment by tlmquintino** [comment]
Order of initialisation is guaranteed in the sense that global objects constructed first are destroyed last (FILO stack)
However 2 static objects in 2 different libraries do not have guarantee who gets constructed first (valid for dynamic and static libraries).

But this is not a problem, because we use the first guarantee to ensure that factories are build before the objects register inside, even when a factory is created in a library separate from the registering object. That is why it works, it is not accidental. This means there is no need for a (single) central registration of builder objects. Each factory is a particular registration centre for objects of that type.

I would still discourage you from building the (eckit, metkit, fdb) stack statically. As you saw, we use `addr` for the configuration files. For an FDB service, those will come handy. 

We do not plan to support the static build of the eckit, metkit, fdb stack of libraries. 
That said, if you want to go the statically link way, indeed you need to use `-Wl,--whole-archive` to ensure the linker includes the self-registration objects.

**Comment by swillner** [comment]
Ok, then I'll close this now ;)
The static order problem I was referring to is the problem that the libraries' global static objects might not be initialized before the factory is used, this was the problem I encountered, a version of the _static initialization fiasco_.
